# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

name: 'Hello World'
description: 'Greet someone'
runs:
  using: "composite"
  steps:
    - name: Set Greeting
      run: echo "Hello world!"
      shell: bash
      
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash

    - name: Run goodbye.sh
      run: ${{ github.action_path }}/deploy.sh
      shell: bash
